### PR TITLE
Change external API to be callback-based

### PR DESCRIPTION
**Pull request by staltz**
Pending on:

- [x] PR https://github.com/ssb-ngi-pointer/ssb-validate2-rsjs-wasm/pull/3 merged and released
- [x] PR https://github.com/ssb-ngi-pointer/ssb-validate2-rsjs-node/pull/6 merged and released
- [x] Versions of the two above updated in this repo's package.json
- [x] CI tests pass in this PR

### CODE REVIEW

**Comment by mycognosist** [comment]
👁️ 👁️

**Comment by staltz** [comment]
@mycognosist This PR is ready. I also updated the version num to 0.5.0, and will release postmerging.

**Review by mycognosist — APPROVED** [review]
Fantastic work! Great attention to detail in updating the `README`.

You might want to consider adding yourself as co-author of the package; you've contributed heaps to this!

**Comment by staltz** [comment]
Thanks! :blush:

**Pull request merged**
